spring.application.name=69-lms-mini-backend
server.port=9292
spring.datasource.url=jdbc\:h2\:mem\:lmsdb\n
spring.datasource.username=sa\n
spring.datasource.password=\n
spring.jpa.hibernate.ddl-auto=create\n
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.h2.console.enabled=true\n
spring.h2.console.path=/h2-console
